# Generated by Django 5.1 on 2024-09-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_url',
            new_name='image',
        ),
    ]
