# Generated by Django 5.1 on 2024-09-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_image_url_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code_deliver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
