# Generated by Django 5.1 on 2024-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_transaction_code_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
