# Generated by Django 5.1 on 2024-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
