# Generated by Django 5.1 on 2024-09-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_itemstatus_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
